server:
  port: 8080   #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: ewallet-service   #current service name to be used by the eureka server
  datasource:
    url: jdbc:mysql://localhost:3306/feedback
    username: root
    password: qwertyuiop
  cloud:
    compatibility-verifier:
      enabled:
        false: management
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  file:
    name: /Users/naveenluhach/Downloads/logs/ewalletservice.log

twitter:
  APIKey: MrJxfbWw2cLVS3mj9k7cZsmbe
  APISecret: ATKjlWaE4GYDQSeOgGppI9SfzpE2THRJm5Lay6gGtmYuhG2wB6
  BearerToken: AAAAAAAAAAAAAAAAAAAAAIsGZgEAAAAAc3CzOoY8mV1FO3QMsBT18FM34W8%3DSmOg2WH46CwQgQjS65u5z7yQ6eSQFSJDeDwlSkkR97THgu15BG

